before_install:
- echo '--colour' > ~/.rspec
- 'echo ''gem: --no-document'' > ~/.gemrc'
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- cp .sample.env .env
- psql -c 'create database "stingerails_test";' -U postgres
branches:
  only:
  - master
cache:
- bundler
language:
- ruby
notifications:
  email:
  - false
rvm:
- 2.1.2
addons:
  postgresql: '9.3'
deploy:
  provider: heroku
  api_key:
    secure: H/OrUyXs9RYatnzcMvPg7X07HXuZV1KzIgk04gdmSKI6r84OfY5clADsQLiEGHjU4ebGY6L1j8owKN7wk7Mw2jXSgHJqWxG7sos4GoqqG8uNA6NnuYNT5BAlFDopsJRravDVxO5ziexTkOrENsjSxOv4MlDTj5qA+xVDU3PrO+8=
  app: tweed-stage
  on:
    repo: blairanderson/stringer
